apiVersion: apps/v1
kind: Deployment
metadata:
  name: feed-api-deployment
  labels:
    app: feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
        - name: udagram-feed
          image: declaudefrancois/udagram-api-feed:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: env-configmap
            - secretRef:
                name: env-secrets
