apiVersion: v1
kind: Service
metadata:
  labels:
    app: feed-api-service
  name: feed
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
