apiVersion: v1
kind: Service
metadata:
  labels:
    app: user-api-service
  name: user
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: user
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
